//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MITD.TestLayer.DataAccess.EF
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    using MITD.TestLayer.Model;
    
    internal partial class TestEntity_Mapping : EntityTypeConfiguration<TestEntity>
    {
        public TestEntity_Mapping()
        {					
    		this.HasKey(t => t.Id);		
    		this.ToTable("TestEntities");
    		this.Property(t => t.TestProperty).IsRequired().HasMaxLength(100);
    	}
    }
}

