// <auto-generated />
namespace MITD.TestLayer.DataAccess.EF.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ver0001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ver0001));
        
        string IMigrationMetadata.Id
        {
            get { return "201212130639076_ver0001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
